### ISSUE TITLE
On Creation of apk

### ISSUE THREAD

**Issue by ehmadjawad** [johnsonsu/react-native-sound-player#138]
I am have an issue after building the apk .
On development mode the this package works fine but when i create apk build the soundplayer does not works.

**Comment by Vente16** [comment]
I have the same issue, any fix?

**Comment by pavanmasterji** [comment]
I have the same issue any idea what is the fix @Vente16 @ehmadjawad @jonasb @assertchris @victor36max

**Comment by assertchris** [comment]
Please link to a repo that reproduces the problem (in the least amount of code possible) or provide version numbers so someone else can create this reproduction. I'm not sure ow any of you expect this to be fixed without providing any of the info required to reproduce this problem.

**Comment by david-allison** [comment]
I get a hang, then a crash only after `gradlew assembleRelease`. 

My use case is calling `SoundPlayer.playUrl` on an mp3 using a `http` url pointing to an IP. 

**Reproduction:**

```typescript
        SoundPlayer.playUrl(`http://download.samplelib.com/mp3/sample-3s.mp3`) 
```

Cause of crash: `MediaPlayer.create()` [may return null](https://developer.android.com/reference/android/media/MediaPlayer#create(android.content.Context,%20android.net.Uri))

<details><summary>Stack trace/additional info</summary>

```
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.media.MediaPlayer.setOnCompletionListener(android.media.MediaPlayer$OnCompletionListener)' on a null object reference
        at com.johnsonsu.rnsoundplayer.RNSoundPlayerModule.prepareUrl(RNSoundPlayerModule.java:210)
        at com.johnsonsu.rnsoundplayer.RNSoundPlayerModule.playUrl(RNSoundPlayerModule.java:80)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:223)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
        at java.lang.Thread.run(Thread.java:923)
```

Fixing the crash likely won't resolve the underlying issue of why `.create()` returns null

Android 11, Google Pixel 3a

I have tried 
* `android:usesCleartextTraffic="true"`
* `<network-security-config>`
* An `<intent-filter>` to the IP

</details>

**Comment by matsuda-argano** [comment]
Add this one to proguard-rules/pro and it should work.

```
-keep class **.R$* {
    public static final int raw.*;
}
```
