### ISSUE TITLE
[BUG] Attempt to invoke virtual method 'int android.media.MediaPlayer.getCurrentPosition()' on a null object reference

### ISSUE THREAD

**Issue by killabeeez** [johnsonsu/react-native-sound-player#88]
**Describe the bug**
 Attempt to invoke virtual method 'int android.media.MediaPlayer.getCurrentPosition()' on a null object reference

 java.lang.NullPointerException: Attempt to invoke virtual method 'int android.media.MediaPlayer.getCurrentPosition()' on a null object reference
        at com.johnsonsu.rnsoundplayer.RNSoundPlayerModule.getInfo(RNSoundPlayerModule.java:107)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
        at android.os.Looper.loop(Looper.java:214)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
        at java.lang.Thread.run(Thread.java:764)

**To Reproduce**
 - SoundPlayer.getInfo();

**Expected behavior**
to work :D

**Platform (please complete the following information):**
 - OS: Android

**Comment by muhammadsarim555** [comment]
I am having the same issue did you find any solution?

**Comment by oriana4r** [comment]
Hi! I had this issue because I was calling `getInfo()` method without a previous audio instance declaration.

**Comment by 256hz** [comment]
I had this issue and looked into the Android code.  The media player is not initialized until the first audio file is loaded.  The solution for me was to load an audio file during the splash screen of the app.
